name: Tuya Energy Logger

on:
  schedule:
    # Run every hour at minute 0 (00:00, 01:00, 02:00, etc.)
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  log-energy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run energy logger
      env:
        TUYA_ACCESS_ID: ${{ secrets.TUYA_ACCESS_ID }}
        TUYA_ACCESS_KEY: ${{ secrets.TUYA_ACCESS_KEY }}
        TUYA_DEVICE_ID: ${{ secrets.TUYA_DEVICE_ID }}
        TUYA_API_ENDPOINT: ${{ secrets.TUYA_API_ENDPOINT }}
      run: |
        python energy_logger.py
        
    - name: Commit and push data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "📊 Energy data update: $(date '+%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
        git push
        
    - name: Log completion
      run: |
        echo "Energy logging completed at $(date)"
